name: Update Submodules

on:
    push:
      branches:
        - main
  
jobs:
    update-submodules:
      runs-on: windows-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure Git
        run: |
          git config --global user.name "NayefNemernn"
          git config --global user.email "nayefnemernn@gmail.com"
      - name: Update Submodules
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Update submodules"
          git push
          